const CategorieBoli = [
    {
        title: 'Boala a ficatului',
        items:[
            {
                id:0,
                Denumire: 'Ultrasunete îmbunătățite cu contrast pentru evaluarea leziunilor hepatice focale (HepFocUS)',
                Sponsor: 'Societatea Romana de Ultrasonografie in Medicina si Biologie',

                Ultima_actualizare_postată: '06-04-2011',
                        Prezentare_generală_a_studiului: 'Rezumat scurt: Scopul studiului este de a evalua valoarea ultrasunetelor cu contrast în evaluarea leziunilor hepatice focale de novo în practica clinică, într-un design prospectiv multicentric. Descriere detaliata: Leziunile hepatice focale (FLL) sunt destul de frecvent descoperite în practica zilnică la ecografie de rutină și uneori necesită utilizarea unor investigații ample pentru un diagnostic corect, crescând astfel costurile și durata diagnosticului. Pe de altă parte, datorită strategiilor de screening pentru pacienții cu ciroză hepatică, FLL sunt descoperite foarte precoce la acești pacienți și trebuie evaluate pentru a stabili o strategie terapeutică (inclusiv transplant, rezecție chirurgicală sau proceduri ecoghidate percutanate). Ecografia cu contrast (CEUS) folosind agenți de contrast de a doua generație este o modalitate imagistică relativ nouă, care permite caracterizarea FLL și permite un diagnostic pozitiv bazat pe modelul vascular al leziunii. Avantajele acestei metode sunt costul redus în comparație cu alte modalități imagistice și faptul că poate fi efectuată imediat după ecografia abdominală standard, astfel încât la aproximativ 5 minute după CEUS (durata totală a acestei investigații) se poate obține un diagnostic de încredere. Locul CEUS în algoritmul de diagnostic al FLL nu este foarte bine stabilit. Federația Europeană a Societăților pentru Ultrasunete în Medicină și Biologie (EFSUMB) a emis primele Ghiduri privind utilizarea CEUS în 2004, revizuite în 2008, în care sunt prezentate principalele indicații ale acestei metode. ',  
                        Contacte_si_locatii: 'Cluj-Napoca, Bucuresti, Constanta, Timisoara, Iasi',
                        Criterii_de_participare: 'Cercetătorii caută persoane care se încadrează într-o anumită descriere, numită criterii de eligibilitate. Câteva exemple ale acestor criterii sunt starea generală de sănătate a unei persoane sau tratamentele anterioare.',
                            Criterii_de_includere: '• pacienții diagnosticați cu FLL de novo la ecografie standard, • vârsta > 18 ani, sex masculin și feminin, • consimțământul informat pentru studiul cu contrast îmbunătățit',
                            Criterii_de_excludere: '• pacienți cu contraindicație pentru studiul cu contrast: subiecți cu infarct cardiac acut, cu insuficiență cardiacă clasa III/IV, cu tulburări de ritm și gravide, • Pacienți diagnosticați cu chisturi simple la ecografie standard (biliare hidatice), •	Pacienți cu FLL cunoscute, de exemplu după tratament percutanat, în care studiul de contrast este utilizat pentru urmărirea pacientului.',
                        Plan_de_studiu: 'Această secțiune oferă detalii despre planul de studiu, inclusiv modul în care este conceput studiul și ce măsoară studiul.',
                            Cum_este_conceput_studiul: 'Detalii de design: Model observațional:Doar caz, Perspectivă temporală:Perspectivă. Coorte si interventii: Leziuni hepatice focal. Leziuni hepatice focale: pacienți descoperiți cu leziuni hepatice focale noi, necaracteristice la ecografie standard',
                            Ce_masoara_studiul: 'MĂSURI DE REZULTAT PRIMAR ',
                                Măsura_rezultatului: 'evaluarea ultrasunetelor cu contrast în evaluarea leziunilor hepatice focale de novo',
                                Descrierea_masurii: 'O examinare CEUS va fi considerată concludentă dacă, după contrast, FLL a avut un model de amplificare tipic conform ghidurilor EFSUMB și neconcludent dacă modelul de amplificare al leziunilor nu a fost în concordanță cu acest ghid.',
                                Interval_de_timp: 'Evaluare 12 luni',
                        Colaboratori_si_anchetatori: 'Aici veți găsi oameni și organizații implicate în acest studiu.',
                                Sponsori: 'Societatea Romana de Ultrasonografie in Medicina si Biologie',
                                COLABORATORI : '•	Centrul de Cercetare in Gastroenterologie si Hepatologie, Craiova, • Clinica de Gastroenterologie si Hepatologie, UMF Timisoara, • Institutul Regional de Gastroenterologie & Hepatologie Prof. dr. Octavian Fodor, •	Institutul Clinic Fundeni, •	Clinica de Gastroenterologie Constanta' ,
                                INVESTIGATORII :  'Nu au fost furnizate informații',

                 Vizualizare_tabel: 'Contacte: Informațiile de contact sunt afișate numai atunci când studiul recrutează subiecți',
                        Datele_înregistrării_studiului: ' ',
                                Primul_trimis: '2011-04-02',
                                Prima_Postat: '06-04-2011',
                                Ultima_actualizare_postată: '06-04-2011',
                                Ultima_verificare: '2011-04',
                        Măsuri_finale: '',
                                Primar_Actual: '(Demis: 2011-04-05): •	evaluarea ultrasunetelor cu contrast în evaluarea leziunilor focale hepatice de novo [Perioadă de timp: evaluare de 12 luni]. o	O examinare CEUS va fi considerată concludentă dacă, după contrast, FLL a avut un model de amplificare tipic conform ghidurilor EFSUMB și neconcludent dacă modelul de amplificare al leziunilor nu a fost în concordanță cu acest ghid.',
                                Secundar_original: 'Nu e disponibil nu e asigurat nu e prevazut',
                        Descrierea_procesului: '',
                                Titlu_scurt: 'Ultrasunete îmbunătățite cu contrast pentru evaluarea leziunilor hepatice focale',
                                Titlu_official: 'Ultrasunete îmbunătățite cu contrast pentru evaluarea leziunilor hepatice focale - un studiu multicentric privind utilitatea în practica clinică0',
                                Rezumat_scurt: 'Scopul studiului este de a evalua valoarea ultrasunetelor cu contrast în evaluarea leziunilor hepatice focale de novo în practica clinică, într-un design prospectiv multicentric.',
                                Descriere_detaliata: 'Leziunile hepatice focale (FLL) sunt destul de frecvent descoperite în practica zilnică la ecografie de rutină și uneori necesită utilizarea unor investigații ample pentru un diagnostic corect, crescând astfel costurile și durata diagnosticului. Pe de altă parte, datorită strategiilor de screening pentru pacienții cu ciroză hepatică, FLL sunt descoperite foarte precoce la acești pacienți și trebuie evaluate pentru a stabili o strategie terapeutică (inclusiv transplant, rezecție chirurgicală sau proceduri ecoghidate percutanate). Ecografia cu contrast (CEUS) folosind agenți de contrast de a doua generație este o modalitate imagistică relativ nouă, care permite caracterizarea FLL și permite un diagnostic pozitiv bazat pe modelul vascular al leziunii. Avantajele acestei metode sunt costul redus în comparație cu alte modalități imagistice și faptul că poate fi efectuată imediat după ecografia abdominală standard, astfel încât la aproximativ 5 minute după CEUS (durata totală a acestei investigații) se poate obține un diagnostic de încredere. Locul CEUS în algoritmul de diagnostic al FLL nu este foarte bine stabilit. Federația Europeană a Societăților pentru Ultrasunete în Medicină și Biologie (EFSUMB) a emis primele Ghiduri privind utilizarea CEUS în 2004, revizuite în 2008, în care sunt prezentate principalele indicații ale acestei metode. Scopul acestui studiu este de a stabili valoarea CEUS în evaluarea FLL de novo în practica clinică.',
                                Tip_de_studiu: 'Observațional',
                                Condiție: '• Hiperplazia nodulară focală a ficatului, •	Boală hepatică toxică cu hiperplazie nodulară focală,  • Metastaze hepatice',
                                Intervenţie: 'Nu e disponibil nu e asigurat nu e prevazut',
                                Grup_de_studiu_Cohorte: '•	: Leziuni hepatice focale, •  Leziuni hepatice focale: pacienți descoperiți cu leziuni hepatice focale noi, necaracteristice la ecografie standard',
                        Informații_de_recrutare: ' ',
                                Starea_recrutarii: 'Stare necunoscută',
                                Înscriere_inițială_estimată: '(Demis: 2011-04-05): 1500',
                                Data_începerii_studiului: '2010-12',
                                Data_de_finalizare_primară_estimată: '2011-2012 (data finală de colectare a datelor pentru măsurarea rezultatului primar)',
                                Data_de_finalizare_a_studiului_estimată: '2011-12',
                                Criterii_de_eligibilitate: 'Criteriile de includere si excludere',
                                Sex: 'Sexe eligibile pentru studiu: Toate',
                                Vârste: '18 ani și peste (adulți, adulți mai în vârstă)',
                                Acceptă_voluntari_sănătoși: 'Nu',
                                Locație_Țări: 'România',

            },

            {
                id:1,
                Denumire: 'Rolul elastografiei de tulpină în stadializarea fibrozei hepatice (auto)',
                Sponsor: 'Universitatea de Medicină și Farmacie Craiova',

                Ultima_actualizare_postată: '08-07-2014',
                        Prezentare_generală_a_studiului: 'Rezumat scurt: Scopul studiului este de a evalua valoarea ultrasunetelor cu contrast în evaluarea leziunilor hepatice focale de novo în practica clinică, într-un design prospectiv multicentric. Descriere detaliata: Leziunile hepatice focale (FLL) sunt destul de frecvent descoperite în practica zilnică la ecografie de rutină și uneori necesită utilizarea unor investigații ample pentru un diagnostic corect, crescând astfel costurile și durata diagnosticului. Pe de altă parte, datorită strategiilor de screening pentru pacienții cu ciroză hepatică, FLL sunt descoperite foarte precoce la acești pacienți și trebuie evaluate pentru a stabili o strategie terapeutică (inclusiv transplant, rezecție chirurgicală sau proceduri ecoghidate percutanate). Ecografia cu contrast (CEUS) folosind agenți de contrast de a doua generație este o modalitate imagistică relativ nouă, care permite caracterizarea FLL și permite un diagnostic pozitiv bazat pe modelul vascular al leziunii. Avantajele acestei metode sunt costul redus în comparație cu alte modalități imagistice și faptul că poate fi efectuată imediat după ecografia abdominală standard, astfel încât la aproximativ 5 minute după CEUS (durata totală a acestei investigații) se poate obține un diagnostic de încredere. Locul CEUS în algoritmul de diagnostic al FLL nu este foarte bine stabilit. Federația Europeană a Societăților pentru Ultrasunete în Medicină și Biologie (EFSUMB) a emis primele Ghiduri privind utilizarea CEUS în 2004, revizuite în 2008, în care sunt prezentate principalele indicații ale acestei metode. ',  
                        Contacte_si_locatii: 'Cluj-Napoca, Bucuresti, Constanta, Timisoara, Iasi',
                        Criterii_de_participare: 'Cercetătorii caută persoane care se încadrează într-o anumită descriere, numită criterii de eligibilitate. Câteva exemple ale acestor criterii sunt starea generală de sănătate a unei persoane sau tratamentele anterioare.',
                            Criterii_de_includere: '• pacienții diagnosticați cu FLL de novo la ecografie standard, • vârsta > 18 ani, sex masculin și feminin, • consimțământul informat pentru studiul cu contrast îmbunătățit',
                            Criterii_de_excludere: '• pacienți cu contraindicație pentru studiul cu contrast: subiecți cu infarct cardiac acut, cu insuficiență cardiacă clasa III/IV, cu tulburări de ritm și gravide, • Pacienți diagnosticați cu chisturi simple la ecografie standard (biliare hidatice), •	Pacienți cu FLL cunoscute, de exemplu după tratament percutanat, în care studiul de contrast este utilizat pentru urmărirea pacientului.',
                        Plan_de_studiu: 'Această secțiune oferă detalii despre planul de studiu, inclusiv modul în care este conceput studiul și ce măsoară studiul.',
                            Cum_este_conceput_studiul: 'Detalii de design: Model observațional:Doar caz, Perspectivă temporală:Perspectivă. Coorte si interventii: Leziuni hepatice focal. Leziuni hepatice focale: pacienți descoperiți cu leziuni hepatice focale noi, necaracteristice la ecografie standard',
                            Ce_masoara_studiul: 'MĂSURI DE REZULTAT PRIMAR ',
                                Măsura_rezultatului: 'evaluarea ultrasunetelor cu contrast în evaluarea leziunilor hepatice focale de novo',
                                Descrierea_masurii: 'O examinare CEUS va fi considerată concludentă dacă, după contrast, FLL a avut un model de amplificare tipic conform ghidurilor EFSUMB și neconcludent dacă modelul de amplificare al leziunilor nu a fost în concordanță cu acest ghid.',
                                Interval_de_timp: 'Evaluare 12 luni',
                        Colaboratori_si_anchetatori: 'Aici veți găsi oameni și organizații implicate în acest studiu.',
                                Sponsori: 'Societatea Romana de Ultrasonografie in Medicina si Biologie',
                                COLABORATORI : '•	Centrul de Cercetare in Gastroenterologie si Hepatologie, Craiova, • Clinica de Gastroenterologie si Hepatologie, UMF Timisoara, • Institutul Regional de Gastroenterologie & Hepatologie Prof. dr. Octavian Fodor, •	Institutul Clinic Fundeni, •	Clinica de Gastroenterologie Constanta' ,
                                INVESTIGATORII :  'Nu au fost furnizate informații',

                 Vizualizare_tabel: 'Contacte: Informațiile de contact sunt afișate numai atunci când studiul recrutează subiecți',
                        Datele_înregistrării_studiului: ' ',
                                Primul_trimis: '2011-04-02',
                                Prima_Postat: '06-04-2011',
                                Ultima_actualizare_postată: '06-04-2011',
                                Ultima_verificare: '2011-04',
                        Măsuri_finale: '',
                                Primar_Actual: '(Demis: 2011-04-05): •	evaluarea ultrasunetelor cu contrast în evaluarea leziunilor focale hepatice de novo [Perioadă de timp: evaluare de 12 luni]. o	O examinare CEUS va fi considerată concludentă dacă, după contrast, FLL a avut un model de amplificare tipic conform ghidurilor EFSUMB și neconcludent dacă modelul de amplificare al leziunilor nu a fost în concordanță cu acest ghid.',
                                Secundar_original: 'Nu e disponibil nu e asigurat nu e prevazut',
                        Descrierea_procesului: '',
                                Titlu_scurt: 'Ultrasunete îmbunătățite cu contrast pentru evaluarea leziunilor hepatice focale',
                                Titlu_official: 'Ultrasunete îmbunătățite cu contrast pentru evaluarea leziunilor hepatice focale - un studiu multicentric privind utilitatea în practica clinică0',
                                Rezumat_scurt: 'Scopul studiului este de a evalua valoarea ultrasunetelor cu contrast în evaluarea leziunilor hepatice focale de novo în practica clinică, într-un design prospectiv multicentric.',
                                Descriere_detaliata: 'Leziunile hepatice focale (FLL) sunt destul de frecvent descoperite în practica zilnică la ecografie de rutină și uneori necesită utilizarea unor investigații ample pentru un diagnostic corect, crescând astfel costurile și durata diagnosticului. Pe de altă parte, datorită strategiilor de screening pentru pacienții cu ciroză hepatică, FLL sunt descoperite foarte precoce la acești pacienți și trebuie evaluate pentru a stabili o strategie terapeutică (inclusiv transplant, rezecție chirurgicală sau proceduri ecoghidate percutanate). Ecografia cu contrast (CEUS) folosind agenți de contrast de a doua generație este o modalitate imagistică relativ nouă, care permite caracterizarea FLL și permite un diagnostic pozitiv bazat pe modelul vascular al leziunii. Avantajele acestei metode sunt costul redus în comparație cu alte modalități imagistice și faptul că poate fi efectuată imediat după ecografia abdominală standard, astfel încât la aproximativ 5 minute după CEUS (durata totală a acestei investigații) se poate obține un diagnostic de încredere. Locul CEUS în algoritmul de diagnostic al FLL nu este foarte bine stabilit. Federația Europeană a Societăților pentru Ultrasunete în Medicină și Biologie (EFSUMB) a emis primele Ghiduri privind utilizarea CEUS în 2004, revizuite în 2008, în care sunt prezentate principalele indicații ale acestei metode. Scopul acestui studiu este de a stabili valoarea CEUS în evaluarea FLL de novo în practica clinică.',
                                Tip_de_studiu: 'Observațional',
                                Condiție: '• Hiperplazia nodulară focală a ficatului, •	Boală hepatică toxică cu hiperplazie nodulară focală,  • Metastaze hepatice',
                                Intervenţie: 'Nu e disponibil nu e asigurat nu e prevazut',
                                Grup_de_studiu_Cohorte: '•	: Leziuni hepatice focale, •  Leziuni hepatice focale: pacienți descoperiți cu leziuni hepatice focale noi, necaracteristice la ecografie standard',
                        Informații_de_recrutare: ' ',
                                Starea_recrutarii: 'Stare necunoscută',
                                Înscriere_inițială_estimată: '(Demis: 2011-04-05): 1500',
                                Data_începerii_studiului: '2010-12',
                                Data_de_finalizare_primară_estimată: '2011-2012 (data finală de colectare a datelor pentru măsurarea rezultatului primar)',
                                Data_de_finalizare_a_studiului_estimată: '2011-12',
                                Criterii_de_eligibilitate: 'Criteriile de includere si excludere',
                                Sex: 'Sexe eligibile pentru studiu: Toate',
                                Vârste: '18 ani și peste (adulți, adulți mai în vârstă)',
                                Acceptă_voluntari_sănătoși: 'Nu',
                                Locație_Țări: 'România',

            }
        ],

        title: 'Covid',
        items:[
            {
                id:0,
                Denumire: 'Cuantificare volumetrică COVID-19 pe tomografie computerizată folosind diagnosticare asistată de computer',
                Sponsor: 'Bogdan Bercean',

                Ultima_actualizare_postată: '2022-05-04',
                        Prezentare_generală_a_studiului: 'Rezumat scurt: Scopul studiului este de a evalua influența diagnosticului asistat de computer asupra procesului de cuantificare a afecțiunii pulmonare asupra tomografiei computerizate la pacienții confirmați cu COVID-19. Descriere detaliata: S-a demonstrat că implicarea pulmonară a pacienților cu COVID-19 este corelată cu rezultatele clinice și a devenit parte a practicii clinice. Chiar dacă pot fi utilizate diferite scoruri, estimarea afecțiunii se face de obicei pe computer tomografie, folosind abilitățile de estimare ale radiologilor, care este un proces extrem de subiectiv. Inteligența artificială este o constantă obiectiv cunoscută și, prin urmare, un potențial complement de radiolog. Acest studiu își propune să studieze efectul utilizării unui software de diagnostic asistat de calculator integrat în practica clinică normală a radiologilor de la Spitalul Județean de Urgență Timișoara. Utilizează configurația de analiză AI-PROBE, care dezactivează ieșirile CAD pentru 50% cazuri alese aleatoriu (control) și apoi compară rapoartele radiologice pentru diferențele dintre cele două brațe.',  
                        Contacte_si_locatii: 'Timisoara',
                        Criterii_de_participare: 'Cercetătorii caută persoane care se încadrează într-o anumită descriere, numită criterii de eligibilitate. Câteva exemple ale acestor criterii sunt starea generală de sănătate a unei persoane sau tratamentele anterioare.',
                            Criterii_de_includere: '•	RT-PCR a confirmat pacienții cu COVID-19',
                            Criterii_de_excludere: '•	15 sau mai puțin',
                        Plan_de_studiu: 'Această secțiune oferă detalii despre planul de studiu, inclusiv modul în care este conceput studiul și ce măsoară studiul.',
                            Cum_este_conceput_studiul: 'Detalii de design: Scopul principal:Diagnostic, Alocare:Randomizat, Model intervențional:Atribuire paralelă, Descrierea modelului intervențional: Ieșirile CAD sunt dezactivate pentru 50% dintre pacienți aleși aleatoriu, care reprezintă grupul de control. Celelalte 50% sunt analizate folosind CAD, Mascare:Singur(Participant), Mascare Descriere: Alocarea aleatorie se face automat de sistemul CAD și nu este vizibilă pentru pacient. Radiologul vede evident ce cazuri au analiza CAD si care nu, ',
                            Ce_masoara_studiul: 'MĂSURI DE REZULTAT PRIMAR ',
                                Măsura_rezultatului: 'Diferența medie a procentului de cuantificare a afecțiunii pulmonare',
                                Descrierea_masurii: 'Măsurarea obiectivă a procentului de afecțiune pulmonară este măsurată în raport cu etichetele la nivel de pixeli. O diferență mai mică înseamnă un rezultat mai bun.',
                                Interval_de_timp: 'La momentul achiziției CT, până la 2 săptămâni',
                        Colaboratori_si_anchetatori: 'Aici veți găsi oameni și organizații implicate în acest studiu.',
                                Sponsori: 'Bogdan Bercean',
                                COLABORATORI : 'Spitalul Judetean de Urgenta Pius Brinzeu Timisoara' ,
                                INVESTIGATORII :  'Nu au fost furnizate informații',

                 Vizualizare_tabel: 'Contacte: Informațiile de contact sunt afișate numai atunci când studiul recrutează subiecți',
                        Datele_înregistrării_studiului: ' ',
                                Primul_trimis: '14-03-2022',
                                Prima_Postat: '16-03-2022',
                                Ultima_actualizare_postată: '2022-05-04',
                                Ultima_verificare: '2022-05',
                        Măsuri_finale: ' ',
                                Primar_Actual: '(Demis: 2022-03-14) •	Diferența medie a procentului de cuantificare a afecțiunii pulmonare [Interval de timp: la momentul achiziției CT, până la 2 săptămâni]. o	Măsurarea obiectivă a procentului de afecțiune pulmonară este măsurată în raport cu etichetele la nivel de pixeli. O diferență mai mică înseamnă un rezultat mai bun.',
                                Secundar_original: 'Nu e disponibil nu e asigurat nu e prevazut',
                        Descrierea_procesului: '',
                                Titlu_scurt: 'Cuantificare volumetrică COVID-19 pe tomografie computerizată folosind diagnosticare asistată de computer',
                                Titlu_official: 'Cuantificare volumetrică COVID-19 pe tomografie computerizată folosind diagnosticare asistată de computer',
                                Rezumat_scurt: 'Scopul studiului este de a evalua influența diagnosticului asistat de computer asupra procesului de cuantificare a afecțiunii pulmonare asupra tomografiei computerizate la pacienții confirmați cu COVID-19.',
                                Descriere_detaliata: 'S-a demonstrat că implicarea pulmonară a pacienților cu COVID-19 este corelată cu rezultatele clinice și a devenit parte a practicii clinice. Chiar dacă pot fi utilizate diferite scoruri, estimarea afecțiunii se face de obicei pe computer tomografie, folosind abilitățile de estimare ale radiologilor, care este un proces extrem de subiectiv. Inteligența artificială este o constantă obiectiv cunoscută și, prin urmare, un potențial complement de radiolog. Acest studiu își propune să studieze efectul utilizării unui software de diagnostic asistat de calculator integrat în practica clinică normală a radiologilor de la Spitalul Județean de Urgență Timișoara. Utilizează configurația de analiză AI-PROBE, care dezactivează ieșirile CAD pentru 50% cazuri alese aleatoriu (control) și apoi compară rapoartele radiologice pentru diferențele dintre cele două brațe.',
                                Tip_de_studiu: 'Intervențional',
                                Condiție: '•  COVID 19',
                                Intervenţie: '•	Test de diagnosticare: analiză CAD; o	CAD arată că radiologul a delimitat automat zonele de potențială afecțiune COVID-19, împreună cu un procent general de afectare pulmonară.',
                                Grup_de_studiu_Cohorte: 'Studiază Armele: •	Experimental: analiză CAD, o	Software-ul de diagnosticare asistată de computer XVision COVID-19 este utilizat de radiolog la momentul analizei CT; o	Intervenții:  	Test de diagnostic: analiză CAD;  •	Fără intervenție: Fără analiză CAD; o	Radiologului nu i se arată nicio analiză CAD', Informații_de_recrutare: ' ',
                                Starea_recrutarii: 'Stare necunoscută',
                                Înscriere_inițială_estimată: '(Demis: 2011-04-05): 100',
                                Data_începerii_studiului: '24-02-2022',
                                Data_de_finalizare_primară_estimată: '2022-03-15 (Data finală de colectare a datelor pentru măsurarea rezultatului primar)',
                                Data_de_finalizare_a_studiului_estimată: '15-03-2022',
                                Criterii_de_eligibilitate: 'Criteriile de includere si excludere',
                                Sex: 'Sexe eligibile pentru studiu: Toate',
                                Vârste: '16 ani și peste (Copil,  Adult,  Adult în vârstă )',
                                Acceptă_voluntari_sănătoși: 'Nu',
                                Locație_Țări: 'România',

            },

            {
                id:1,
                Denumire: 'Impactul pandemiei de Covid 19 asupra pregătirii rezidenților de chirurgie generală',
                Sponsor: 'Universitatea de Medicină și Farmacie Iuliu Hatieganu',

                Ultima_actualizare_postată: '28-10-2021',
                        Prezentare_generală_a_studiului: 'Rezumat scurt: Procesul educațional al rezidenților de chirurgie generală este un pas foarte important în cariera fiecărui chirurg, care este adesea trecut cu vederea sau neglijat. Pandemia de Covid-19 a provocat schimbări profunde în activitatea medicală în general și în procesul de formare a tinerilor medici în special. Descriere detaliata: Studiul nostru își propune să evalueze impactul pandemiei de Covid-19 asupra procesului educațional al rezidenților de chirurgie generală, printr-un studiu comparativ. Răspunsurile medicilor rezidenți la un chestionar, în două perioade de timp diferite, vor fi comparate: pre-Covid (decembrie 2019) și Covid (decembrie 2020).',  
                        Contacte_si_locatii: 'Cluj-Napoca',
                        Criterii_de_participare: 'Cercetătorii caută persoane care se încadrează într-o anumită descriere, numită criterii de eligibilitate. Câteva exemple ale acestor criterii sunt starea generală de sănătate a unei persoane sau tratamentele anterioare.',
                            Criterii_de_includere: '•	Rezidenți de chirurgie generală,  • Peste al doilea an de rezidență, •	Program de rezidenta in Centrul Medical Cluj-Napoca',
                            Criterii_de_excludere: '•	Răspunsuri incomplete la chestionar, •	Refuzul de a fi inclus în studiu',
                        Plan_de_studiu: 'Această secțiune oferă detalii despre planul de studiu, inclusiv modul în care este conceput studiul și ce măsoară studiul.',
                            Cum_este_conceput_studiul: 'Detalii de design: Model observațional:Cohortă, Perspectivă temporală:Alte',
                            Ce_masoara_studiul: 'MĂSURI DE REZULTAT PRIMAR ',
                                Măsura_rezultatului: 'Impactul pandemiei asupra procesului educațional',
                                Descrierea_masurii: 'Participare activa in sala de operatie (ore/zi, zi/saptamana), Educatie teoretica (ore/saptamana), posibilitati de pregatire extracurriculara.',
                                Interval_de_timp: 'decembrie 2019-decembrie 2020',
                        Colaboratori_si_anchetatori: 'Aici veți găsi oameni și organizații implicate în acest studiu.',
                                Sponsori: 'Universitatea de Medicină și Farmacie Iuliu Hatieganu',
                                COLABORATORI : 'Nu au fost furnizate informații' ,
                                INVESTIGATORII :  'Nu au fost furnizate informații',

                 Vizualizare_tabel: 'Contacte: Informațiile de contact sunt afișate numai atunci când studiul recrutează subiecți',
                        Datele_înregistrării_studiului: ' ',
                                Primul_trimis: '2021-10-05',
                                Prima_Postat: '2021-10-06',
                                Ultima_actualizare_postată: '28-10-2021',
                                Ultima_verificare: '2021-10',
                        Măsuri_finale: '',
                                Primar_Actual: '(Demis: 2021-10-21): •	Impactul pandemiei asupra procesului educațional [Perioa de timp: decembrie 2019-decembrie 2020], o	Participare activa in sala de operatie (ore/zi, zi/saptamana), Educatie teoretica (ore/saptamana), posibilitati de pregatire extracurriculara',
                                Secundar_original: 'Demis: 2021-10-05). •	Impactul pandemiei asupra procesului educațional [Perioa de timp: decembrie 2019-decembrie 2020]',
                        Descrierea_procesului: '',
                                Titlu_scurt: 'Impactul pandemiei de Covid 19 asupra pregătirii rezidenților de chirurgie generală',
                                Titlu_official: 'Impactul pandemiei de Covid 19 asupra pregătirii rezidenților de chirurgie generală',
                                Rezumat_scurt: 'Procesul educațional al rezidenților de chirurgie generală este un pas foarte important în cariera fiecărui chirurg, care este adesea trecut cu vederea sau neglijat. Pandemia de Covid-19 a provocat schimbări profunde în activitatea medicală în general și în procesul de formare a tinerilor medici în special. Studiul nostru își propune să evalueze impactul pandemiei de Covid-19 asupra procesului educațional al rezidenților de chirurgie generală, printr-un studiu comparativ. Răspunsurile medicilor rezidenți la un chestionar, în două perioade de timp diferite, vor fi comparate: pre-Covid (decembrie 2019) și Covid (decembrie 2020).',
                                Descriere_detaliata: 'Nu e disponibil nu e asigurat nu e prevazut',
                                Tip_de_studiu: 'Observațional',
                                Condiție: 'Covid-19 pandemie, Probleme educaționale',
                                Intervenţie: '•	Alte: Pregătire în chirurgie,  o	Studiul evaluează procesul de pregătire al rezidenților de chirurgie generală – în chirurgie clasică, precum și în chirurgie laparoscopică, de la activitatea spitalicească până la activitățile extracurriculare.',
                                Grup_de_studiu_Cohorte: '•	: era pre-Covid,  o	Intervenții:, 	Altele: Training in chirurgie, •	: Era Covid, o	Intervenții: 	,Altele: Training in chirurgie',Informații_de_recrutare: ' ',
                                Starea_recrutarii: 'Stare necunoscută',
                                Înscriere_inițială_estimată: '(Demis: 2011-04-05): 1500',
                                Data_începerii_studiului: '2010-12',
                                Data_de_finalizare_primară_estimată: '2011-2012 (data finală de colectare a datelor pentru măsurarea rezultatului primar)',
                                Data_de_finalizare_a_studiului_estimată: '2011-12',
                                Criterii_de_eligibilitate: 'Criteriile de includere si excludere',
                                Sex: 'Sexe eligibile pentru studiu: Toate',
                                Vârste: '20 de ani și mai mult (Adult,  Adult în vârstă ',
                                Acceptă_voluntari_sănătoși: 'Da',
                                Locație_Țări: 'România',

            }
        ],

        title: 'Accident Cerebral Vascular',
        items:[
            {
                id:0,
                Denumire: 'Recuperare medicală și reintegrare socială pentru pacienții post-accident vascular cerebral folosind realitatea virtuală',
                Sponsor: 'Universitatea Transilvania din Brasov',

                Ultima_actualizare_postată: '2020-06-18',
                        Prezentare_generală_a_studiului: 'Rezumat scurt: Aplicarea terapiei cu realitate virtuală și a terapiei ocupaționale versus fizioterapie și terapie ocupațională standard la pacienții cu sechele post-accident vascular cerebral, folosind instrumente de evaluare specifice, programe standard de fizioterapie și terapie ocupațională. Descriere detaliata: 1.	Evaluarea clinică și funcțională inițială și finală a pacienților cu sechele post-AVC, păstrarea și utilizarea datelor obținute. 2.	Colectarea și accesul datelor demografice și clinice ale pacienților incluși în studiu (respectând principiul confidențialității și nepublicării datelor cu caracter personal) numai de către personalul implicat în proiectul de cercetare și care lucrează în cadrul Spitalului Clinic de Psihiatrie și Neurologie Brașov. 3.	Aplicarea terapiei cu Realitatea Virtuală și a terapiei ocupaționale versus și a fizioterapiei și terapiei ocupaționale standard la pacienții care îndeplinesc criteriile de includere în studiu (flexie și abducție scapulohumerală de cel puțin 20 de grade, flexie cot de cel puțin 20 de grade, flexie șold și genunchi de cel puțin 20 de grade, fără afazie severă sau tulburări de comportament/cognitive severe). 4.	Utilizarea datelor obtinute din aplicarea terapiei cu Realitatea Virtuala la domiciliu, prin Telereabilitare, daca pacientii isi procura singuri sau prin sponsorizare/donatie echipamentele necesare continuarii programului de terapie cu Realitatea Virtuala la domiciliu, tinand cont ca tehnologia achizitionata prin proiect permite acest.',  
                        Contacte_si_locatii: 'Brasov',
                        Criterii_de_participare: 'Cercetătorii caută persoane care se încadrează într-o anumită descriere, numită criterii de eligibilitate. Câteva exemple ale acestor criterii sunt starea generală de sănătate a unei persoane sau tratamentele anterioare.',
                            Criterii_de_includere: '•	supraviețuitorii AVC după faza acută, cel puțin 6 săptămâni după AVC; •	supraviețuitorii accidentului vascular cerebral în cel mult 4 ani după accident vascular cerebral, • flexie de cel puțin 30 de grade și abducție scapulohumerală împotriva gravitației; • flexia cotului de cel putin 30 de grade; • flexia șoldului de cel puțin 30 de grade; • flexia genunchiului de cel putin 30 de grade',
                            Criterii_de_excludere: '•	fără tulburări cognitive severe, • fără afazie senzorială globală sau transcorticală, • fără alte disfuncții la nivelul extremității superioare, cum ar fi intervenții chirurgicale, fracturi, artrită la umăr sau durere severă, •	fără alte disfuncții la nivelul extremității inferioare, cum ar fi intervenții chirurgicale, fracturi, artrită sau dureri severe, • fara anemie; • fara fibrilatie atriala; • fără insuficiență cardiacă clasa IV NYHA',
                        Plan_de_studiu: 'Această secțiune oferă detalii despre planul de studiu, inclusiv modul în care este conceput studiul și ce măsoară studiul.',
                            Cum_este_conceput_studiul: 'Detalii de design: Scopul principal: Altul, Alocare:Randomizat, Model intervențional: alocare în paralel, Mascare: singur (participant) ',
                            Ce_masoara_studiul: 'MĂSURI DE REZULTAT PRIMAR ',
                                Măsura_rezultatului: 'Numărul de pacienți pentru care terapia de realitate virtuală personalizată este mai eficientă decât kinetoterapie personalizată standard în recuperarea sechelelor post-accident vascular cerebral.',
                                Descrierea_masurii: '•	Determinarea factorilor și parametrilor care influențează sau îmbunătățesc capacitatea de recuperare după accident vascular cerebral folosind noi metode de recuperare, cum ar fi realitatea virtuală neimersivă. • Instrumentele de evaluare sunt: evaluarea Fugl-Meyer pentru extremitatea superioară (FMUE), evaluarea Fugl-Meyer pentru extremitatea inferioară (FMLE), Scala Rankin modificată (MRS), Măsura independenței funcționale (FIM), Intervalul activ de Mișcare (AROM), Testarea manuală a mușchilor (MMT), Scara Ashworth modificată (MAS), Testul de atingere funcțională (FRT) și Testul Timed Up and Go (TUG). • Pacienții sunt evaluați de medicii de recuperare (fiziatri) cu privire la FIM, MAS și MRS. În timp ce FMUE, FMLE, AROM, MMT, FRT, TUG sunt evaluate de kinetoterapeuți instruiți, cu cel puțin 5 ani de experiență în kinetoterapie și evaluare a sechelelor AVC.',
                                Interval_de_timp: 'Un an de la începutul cercetării',
                        Colaboratori_si_anchetatori: 'Aici veți găsi oameni și organizații implicate în acest studiu.',
                                Sponsori: 'Universitatea Transilvania din Brasov',
                                COLABORATORI : 'Spitalul Clinic de Psihiatrie si Neurologie Brasov' ,
                                INVESTIGATORII :  'Investigator principal: Felician Stancioiu, Fundatia Bio-Forum',

                 Vizualizare_tabel: 'Contacte: Informațiile de contact sunt afișate numai atunci când studiul recrutează subiecți',
                        Datele_înregistrării_studiului: ' ',
                                Primul_trimis: '2020-06-11',
                                Prima_Postat: '2020-06-18',
                                Ultima_actualizare_postată: '2020-06-18',
                                Ultima_verificare: '2020-06',
                        Măsuri_finale: ' ',
                                Primar_Actual: '(Demis: 2020-06-15): Numărul de pacienți pentru care terapia de realitate virtuală personalizată este mai eficientă decât kinetoterapie personalizată standard în recuperarea sechelelor post-accident vascular cerebral. [Perioadă de timp: Un an de la începutul cercetării]; • Determinarea factorilor și parametrilor care influențează sau îmbunătățesc capacitatea de recuperare după accident vascular cerebral folosind noi metode de recuperare, cum ar fi realitatea virtuală neimersivă. ○ Instrumentele de evaluare sunt: evaluarea Fugl-Meyer pentru extremitatea superioară (FMUE), evaluarea Fugl-Meyer pentru extremitatea inferioară (FMLE), Scala Rankin modificată (MRS), Măsura independenței funcționale (FIM), Intervalul activ de Mișcare (AROM), Testarea manuală a mușchilor (MMT), Scara Ashworth modificată (MAS), Testul de atingere funcțională (FRT) și Testul Timed Up and Go (TUG). ○ Pacienții sunt evaluați de medicii de recuperare (fiziatri) cu privire la FIM, MAS și MRS. În timp ce FMUE, FMLE, AROM, MMT, FRT, TUG sunt evaluate de kinetoterapeuți instruiți, cu cel puțin 5 ani de experiență în kinetoterapie și evaluare a sechelelor AVC.',
                                Secundar_original: '(Demis: 2018-05-21): Numărul de pacienți la care bolile de inimă și alte afecțiuni ale vârstnicilor, vârsta sau sexul influențează capacitatea de recuperare a pacienților post-AVC. [Perioadă de timp: Un an de la începutul cercetării]; •	Colectarea datelor referitoare la vârsta, sexul, timpul după AVC, alte afecțiuni prezente (cum ar fi hipertensiunea arterială, dislipidemia, diabetul, boala coronariană ischemică etc.) și determinarea legăturilor dintre capacitatea de recuperare post-AVC și acești factori folosind programe software statistice și analize . ',
                        Descrierea_procesului: '',
                                Titlu_scurt: 'Recuperare medicală și reintegrare socială pentru pacienții post-accident vascular cerebral folosind realitatea virtuală',
                                Titlu_official: 'Recuperare medicală și reintegrare socială pentru pacienții post-accident vascular cerebral cu sechele folosind realitatea virtuală',
                                Rezumat_scurt: 'Aplicarea terapiei cu realitate virtuală și a terapiei ocupaționale versus fizioterapie și terapie ocupațională standard la pacienții cu sechele post-accident vascular cerebral, folosind instrumente de evaluare specifice, programe standard de fizioterapie și terapie ocupațională.',
                                Descriere_detaliata: '1.Evaluarea clinică și funcțională inițială și finală a pacienților cu sechele post-AVC, păstrarea și utilizarea datelor obținute. 2.Colectarea și accesul datelor demografice și clinice ale pacienților incluși în studiu (respectând principiul confidențialității și nepublicării datelor cu caracter personal) numai de către personalul implicat în proiectul de cercetare și care lucrează în cadrul Spitalului Clinic de Psihiatrie și Neurologie Brașov. 3.Aplicarea terapiei cu Realitatea Virtuală și a terapiei ocupaționale versus și a fizioterapiei și terapiei ocupaționale standard la pacienții care îndeplinesc criteriile de includere în studiu (flexie și abducție scapulohumerală de cel puțin 20 de grade, flexie cot de cel puțin 20 de grade, flexie șold și genunchi de cel puțin 20 de grade, fără afazie severă sau tulburări de comportament/cognitive severe). 4.	Utilizarea datelor obtinute din aplicarea terapiei cu Realitatea Virtuala la domiciliu, prin Telereabilitare, daca pacientii isi procura singuri sau prin sponsorizare/donatie echipamentele necesare continuarii programului de terapie cu Realitatea Virtuala la domiciliu, tinand cont ca tehnologia achizitionata prin proiect permite acest.',
                                Tip_de_studiu: 'Intervențional',
                                Condiție: 'Sechele de accident vascular cerebral',
                                Intervenţie: 'Altele: terapie de realitate virtuală neimersivă: • Exerciții de terapie de realitate virtuală (VR) non-imersive, bazate pe evaluare și exerciții de terapie ocupațională, pentru extremitatea superioară sau inferioară. Pentru extremitatea superioară, zilnic, de la 20-40 la minute de terapie VR plus 20-40 de minute de exerciții de terapie ocupațională, în funcție de capacitatea pacientului de antrenament VR, întrucât întreaga terapie pentru extremitatea superioară nu depășește 60 de minute. Pentru extremitatea inferioară, de la 20-40 la minute de terapie VR plus 20-40 de minute de exerciții de terapie ocupațională, în funcție de capacitatea pacientului de antrenament VR, deoarece întreaga terapie pentru extremitatea inferioară nu depășește 60 de minute. Protocolul pentru exercițiile de terapie ocupațională pentru mână a inclus utilizarea plăcii canadiane, antrenament de prindere groasă și subțire, prinderea laterală și palmară, precum și sarcini de întărire a extensoarelor încheieturii mâinii. Pentru gleznă și picior s-au folosit exerciții analitice și de dexteritate folosind terapia cu oglindă și singur. Altele: Fizioterapie standard •	Program standard de kinetoterapie, bazat pe evaluare, plus exerciții de terapie ocupațională, pentru extremitatea superioară sau inferioară. Pentru extremitatea superioară, zilnic, 30 de minute de kinetoterapie standard plus 30 de minute de exerciții de terapie ocupațională. Pentru extremitatea inferioară, zilnic, 30 de minute de kinetoterapie standard plus 30 de minute de exerciții de terapie ocupațională. Protocolul pentru exercițiile de terapie ocupațională pentru mână a inclus utilizarea plăcii canadiane, antrenament de prindere groasă și subțire, prinderea laterală și palmară, precum și sarcini de întărire a extensoarelor încheieturii mâinii. Pentru gleznă și picior s-au folosit exerciții analitice și de dexteritate.	Alte nume: Exerciții de terapie ocupațională',
                                Grup_de_studiu_Cohorte: 'Studiază Armele: Comparator activ: Grup de control • Fizioterapie standard și OT •	Intervenții: 	Altele: Fizioterapie standard. Experimental: Experimental •	Terapie în realitate virtuală și OT •	Intervenții: 	Altele: terapie de realitate virtuală neimersivă', 
                                Informații_de_recrutare: ' ',
                                Starea_recrutarii: 'Suspendata',
                                Înscriere_inițială_estimată: '(Demis: 2020-06-15): 52',
                                Data_începerii_studiului: '2019-07-18',
                                Data_de_finalizare_primară_estimată: '2020-02-28 (Data finală de colectare a datelor pentru măsurarea rezultatului primar)',
                                Data_de_finalizare_a_studiului_estimată: '2020-12-31',
                                Criterii_de_eligibilitate: 'Criteriile de includere si excludere',
                                Sex: 'Sexe eligibile pentru studiu: Toate',
                                Vârste: '18 ani până la 85 de ani (adulți, adulți în vârstă)',
                                Acceptă_voluntari_sănătoși: 'Nu',
                                Locație_Țări: 'România',

            },

            {
                id:1,
                Denumire: 'Terapia cu unde de șoc extracorporală și strategie de evaluare printr-un instrument nou de analiză a mersului pentru spasticitatea post-accident vascular cerebral',
                Sponsor: 'Universitatea de Medicină și Farmacie Carol Davila',

                Ultima_actualizare_postată: '2023-02-16',
                        Prezentare_generală_a_studiului: 'Rezumat scurt: Scopul acestui studiu este de a evalua în mod obiectiv eficacitatea terapiei cu unde de șoc radial extracorporal (rESWT) și a programului de kinetoterapie convențională asupra modelului de mers printr-un nou sistem de analiză a mersului care cuprinde parametrii spațiotemporali și cinematici și de a corela rezultatele cu evaluarea clinică. Descriere detaliata: Scopul acestui studiu observațional a fost de a evalua în mod obiectiv efectele terapiei cu unde de șoc radiale extracorporale și ale programului de kinetoterapie convențională asupra modelului de mers, variabilelor spațio-temporale (lungimea pasului, timpul ciclului pasului, flexia-extensia piciorului, pronația-supinația, pronația-supinația). și flexia-extensia piciorului) și parametri cinematici (flexia-extensia trunchiului, flexia laterală a trunchiului, flexia-extensia șoldului, flexia-extensia genunchiului, flexia-extensia gleznei) printr-un nou sistem de analiză a mersului și corelarea constatărilor cu rezultatele clinice precum ca scala Ashworth modificată (MAS), gama pasivă de mișcare (PROM), scorul Clonus, scara vizuală analogică (VAS), instrumentul de evaluare Tinetti, categoriile de ambulare funcțională (FAC). Modelul de mers al pacienților post-accident vascular cerebral înainte și după livrarea rESWT și programul convențional de reabilitare va fi evaluat clinic și, de asemenea, printr-o bandă de alergare instrumentată (Walker View) în ceea ce privește parametrii de mers spațiotemporal și cinematic.',  
                        Contacte_si_locatii: 'Bucuresti',
                        Criterii_de_participare: 'Cercetătorii caută persoane care se încadrează într-o anumită descriere, numită criterii de eligibilitate. Câteva exemple ale acestor criterii sunt starea generală de sănătate a unei persoane sau tratamentele anterioare.',
                            Criterii_de_includere: '• supraviețuitorii AVC după faza acută, cel puțin 6 săptămâni după AVC; • suferit de un accident vascular cerebral hemoragic sau ischemic și erau în faza subacută sau cronică; • nu a avut antecedente de accident vascular cerebral; • avea spasticitate post-accident vascular cerebral la membrul inferior și grad de spasticitate ≥1 pe Scala Ashworth modificată (MAS); • intensitatea durerii măsurată pe scala vizuală analogică (VAS) ≥1; • capacitatea de a sta în picioare și de a merge neasistat timp de cel puțin 30 de secunde; • pacienți adulți (>18 ani).',
                            Criterii_de_excludere: '•	alte afectiuni neurologice, musculo-scheletice, ortopedice sau cardiovasculare; -- tulburări cognitive severe, afazie severă sau incapacitate de a înțelege sau executa instrucțiuni; •	modificări ale medicației antispastice și ale dozei sau modificări ale medicației analgezice; •	miopatie; • grad de spasticitate severă; • tulburări de câmp vizual sau hemineglect; • anticoagulante sau orice contraindicație pentru a primi terapie radială cu undă de șoc extracorporală (rESWT) sau orice contraindicație pentru a primi ședințe de kinetoterapie.',
                        Plan_de_studiu: 'Această secțiune oferă detalii despre planul de studiu, inclusiv modul în care este conceput studiul și ce măsoară studiul.',
                            Cum_este_conceput_studiul: 'Detalii de design: Model observațional: Doar caz; Perspectivă temporală: prospectivă',
                            Ce_masoara_studiul: 'MĂSURI DE REZULTAT PRIMAR ',
                                Măsura_rezultatului: 'Modificarea gradului de spasticitate',
                                Descrierea_masurii: 'Scala Ashworth modificată (MAS); variază de la 0 (fără creștere a tonusului muscular) la 5 (membrul rigid în flexie sau extensie). Cu cât scorul este mai mic, cu atât gradul de spasticitate este mai scăzut, astfel un rezultat mai bun.',
                                Interval_de_timp: 'Modificare față de scala de bază modificată Ashworth la 14 zile',
                        Colaboratori_si_anchetatori: 'Aici veți găsi oameni și organizații implicate în acest studiu.',
                                Sponsori: 'Universitatea de Medicină și Farmacie Carol Davila',
                                COLABORATORI : 'Nu au fost furnizate informații' ,
                                INVESTIGATORII :  'Director de studiu: Mihai Berteanu, Spitalul Universitar de Urgență Elias, București, România',

                 Vizualizare_tabel: 'Contacte: Informațiile de contact sunt afișate numai atunci când studiul recrutează subiecți',
                        Datele_înregistrării_studiului: ' ',
                                Primul_trimis: '2021-12-24',
                                Prima_Postat: '2022-01-25',
                                Ultima_actualizare_postată: '2023-02-16',
                                Ultima_verificare: '2023-02',
                        Măsuri_finale: '',
                                Primar_Actual: '(Demis: 2022-01-11): Modificarea gradului de spasticitate [Perioadă de timp: modificare față de scara Ashworth modificată la valoarea de bază la 14 zile]. • Scala Ashworth modificată (MAS); variază de la 0 (fără creștere a tonusului muscular) la 5 (membrul rigid în flexie sau extensie). Cu cât scorul este mai mic, cu atât gradul de spasticitate este mai scăzut, astfel un rezultat mai bun.',
                                Secundar_original: '(Demis: 2022-01-11): Modificarea amplitudinii pasive a mișcării gleznei [Cadru de timp: modificare față de intervalul de mișcare pasiv la 14 zile de la valoarea de bază]. • Gama pasivă de mișcare (PROM); flexie 0-30 grade, extensie 0-50 grade, pronatie 0-30 grade, supinatie 0-60 grade. Scorurile mai mari definesc o gamă de mișcare sporită și mai bună. Modificarea intensității durerii [Perioadă de timp: modificare față de scala analogică vizuală inițială la 14 zile]. • Scala vizuală analogică (VAS); cu cât este mai mare valoarea pe linia de 0,1 metri, cu atât intensitatea durerii este mai mare, începând de la 0 (nicio durere) până la 10 (cea mai mare intensitate a durerii experimentată vreodată). Modificarea duratei pasului [Perioadă de timp: modificare față de lungimea pasului de referință la 14 zile]. • Lungimea pasului (metri); variază de la 0-0,5 metri, cu cât lungimea pasului este mai mare duce la un rezultat mai bun. Schimbare de flexie-extensie a genunchiului [Cadru de timp: modificare față de flexia-extensia genunchiului de bază la 14 zile]. • Flexie-extensie genunchi; Valoarea unghiului maxim și minim în planul sagital al genunchiului, de la 0 grade în extensie completă la 140-150 grade în flexie maximă.',
                        Descrierea_procesului: '',
                                Titlu_scurt: 'Terapia cu unde de șoc extracorporală și strategie de evaluare printr-un instrument nou de analiză a mersului pentru spasticitatea post-accident vascular cerebral',
                                Titlu_official: 'Eficacitatea terapiei cu unde de șoc extracorporale și a strategiei de evaluare printr-un instrument nou de analiză a mersului pentru spasticitatea post-accident vascular cerebral în timpul pandemiei de COVID-19',
                                Rezumat_scurt: 'Scopul acestui studiu este de a evalua în mod obiectiv eficacitatea terapiei cu unde de șoc radial extracorporal (rESWT) și a programului de kinetoterapie convențională asupra modelului de mers printr-un nou sistem de analiză a mersului care cuprinde parametrii spațiotemporali și cinematici și de a corela rezultatele cu evaluarea clinică.',
                                Descriere_detaliata: 'Scopul acestui studiu observațional a fost de a evalua în mod obiectiv efectele terapiei cu unde de șoc radiale extracorporale și ale programului de kinetoterapie convențională asupra modelului de mers, variabilelor spațio-temporale (lungimea pasului, timpul ciclului pasului, flexia-extensia piciorului, pronația-supinația, pronația-supinația). și flexia-extensia piciorului) și parametri cinematici (flexia-extensia trunchiului, flexia laterală a trunchiului, flexia-extensia șoldului, flexia-extensia genunchiului, flexia-extensia gleznei) printr-un nou sistem de analiză a mersului și corelarea constatărilor cu rezultatele clinice precum ca scala Ashworth modificată (MAS), gama pasivă de mișcare (PROM), scorul Clonus, scara vizuală analogică (VAS), instrumentul de evaluare Tinetti, categoriile de ambulare funcțională (FAC). Modelul de mers al pacienților post-accident vascular cerebral înainte și după livrarea rESWT și programul convențional de reabilitare va fi evaluat clinic și, de asemenea, printr-o bandă de alergare instrumentată (Walker View) în ceea ce privește parametrii de mers spațiotemporal și cinematic.',
                                Tip_de_studiu: 'Observațional',
                                Condiție: '• Accident vascular cerebral, ischemic; • Accident vascular cerebral hemoragic; • Spasticitate, mușchi; • Mers spastic',
                                Intervenţie: 'Altele: Terapie radială cu unde de șoc extracorporală și kinetoterapie convențională; • Programul de kinetoterapie convențională va consta în strategii de verticalizare, exerciții de gamă de mișcări, exerciții de întindere și întărire a mușchilor, antrenament de poziție și echilibru, exerciții de stabilitate de bază, antrenament de mers, antrenament funcțional, crioterapie sau căldură locală timp de 1 oră/zi, 5 zile/săptămână. timp de 2 săptămâni. • În ceea ce privește livrarea rESWT, pe joncțiunea miotendinoasă a tricepsului sural se vor aplica 2000 de injecții cu o frecvență de 10 Hz și o densitate energetică de 60 mJ, 7 min/ședință, 1 ședință/săptămână timp de 2 săptămâni.',
                                Grup_de_studiu_Cohorte: 'Grup de studiu: • Pacienții considerați eligibili vor forma grupul de studiu și vor începe programul de kinetoterapie convențională și livrarea terapiei cu unde de șoc extracorporale radiale (rESWT). •	Intervenții: 	Altele: Terapie radială cu unde de șoc extracorporală și kinetoterapie convențională ',
                                Starea_recrutarii: 'Completat',
                                Înscriere_inițială_estimată: '(Demis: 2023-02-15): 15',
                                Data_începerii_studiului: '2021-03-01',
                                Data_de_finalizare_primară_estimată: '2022-06-01 (Data finală de colectare a datelor pentru măsurarea rezultatului primar)',
                                Data_de_finalizare_a_studiului_estimată: '2022-08-01',
                                Criterii_de_eligibilitate: 'Criteriile de includere si excludere',
                                Sex: 'Sexe eligibile pentru studiu: Toate',
                                Vârste: '18 ani și peste (adulți, adulți mai în vârstă) ',
                                Acceptă_voluntari_sănătoși: 'Nu',
                                Locație_Țări: 'România',

            }
        ]
    }
]